site_name: CAF-So

theme:
  name: "material"
  palette:
    primary: cyan
  logo: images/caf-so.jpg

nav:
  - Home: index.md
  - Deposit: deposit.md
  - Withdraw: withdraw.md
  - Margin: margin.md
  - Info: info.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox